//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(PagosMetadata))]

    public partial class Pagos
    {
        public int idDebt { get; set; }
        public long amount { get; set; }
        public string status { get; set; }
        public int idHome { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> idCollectionPlan { get; set; }
    
        public virtual pCobro pCobro { get; set; }
        public virtual Residencia Residencia { get; set; }
    }
}
