//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservaciones
    {
        public int idReservation { get; set; }
        public string status { get; set; }
        public int idHome { get; set; }
        public System.DateTime date { get; set; }
        public int startingHour { get; set; }
        public int finishingHour { get; set; }
        public int idArea { get; set; }
    
        public virtual AreasComunes AreasComunes { get; set; }
    }
}
