//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(ResidenciaMetadata))]
    public partial class Residencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Residencia()
        {
            this.Pagos = new HashSet<Pagos>();
        }
    
        public int idHome { get; set; }
        public Nullable<int> idUser { get; set; }
        public string owner { get; set; }
        public int nResidents { get; set; }
        public Nullable<int> nCars { get; set; }
        public Nullable<int> nCondominium { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> dateBegin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
